package model;

/**
 * Model class representing a Contact entity in the Phone Book.
 */
public class Contact {
    private int id;
    private int userId;
    private String name;
    private String phoneNumber;
    private String email;
    private String address;
    private boolean favorite;

    /**
     * Default constructor.
     */
    public Contact() {
    }

    /**
     * Constructor for creating a new Contact before saving to the database.
     * (ID is generated by the database).
     */
    public Contact(int userId, String name, String phoneNumber, String email, String address, boolean favorite) {
        this.userId = userId;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.address = address;
        this.favorite = favorite;
    }

    /**
     * Full constructor for retrieving a Contact from the database.
     */
    public Contact(int id, int userId, String name, String phoneNumber, String email, String address, boolean favorite) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.address = address;
        this.favorite = favorite;
    }

    // --- Getters and Setters ---

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public boolean isFavorite() {
        return favorite;
    }

    public void setFavorite(boolean favorite) {
        this.favorite = favorite;
    }

    // --- toString ---

    @Override
    public String toString() {
        return "Contact{" +
                "id=" + id +
                ", userId=" + userId +
                ", name='" + name + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", email='" + email + '\'' +
                ", address='" + address + '\'' +
                ", favorite=" + favorite +
                '}';
    }
}
