package model;

import java.sql.Timestamp;

/**
 * Model class representing a User entity.
 */
public class User {
    private int id;
    private String username;
    private String password;
    private Timestamp createdAt;

    /**
     * Default constructor.
     */
    public User() {
    }

    /**
     * Constructor for creating a new User before inserting to the database.
     * (ID and createdAt are generated by the database).
     *
     * @param username the username
     * @param password the password
     */
    public User(String username, String password) {
        this.username = username;
        this.password = password;
    }

    /**
     * Full constructor for retrieving a User from the database.
     *
     * @param id        the user ID
     * @param username  the username
     * @param password  the password
     * @param createdAt the timestamp of creation
     */
    public User(int id, String username, String password, Timestamp createdAt) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.createdAt = createdAt;
    }

    // --- Getters and Setters ---

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Timestamp getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    // --- toString ---

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='[PROTECTED]'" + 
                ", createdAt=" + createdAt +
                '}';
    }
}
